dotVersionFiles:
  - sdk/rust/core/Cargo.toml
  - sdk/rust/codegen/Cargo.toml
  - sdk/assemblyscript/package.json
  - sdk/typescript/package.json

preMakeTargets:
  - test

postMakeTargets:
  - crate/publish
  - npm/publish
